### ISSUE TITLE
Error: hex.includes is not a function

### ISSUE THREAD

**Issue by macsupport** [Cap-go/tailwind-capacitor#16]
Just installed your plugin and when running

npx tailwindcss -i ./src/css/styles.css -o ./src/css/tailwind.css --minify

I get the following error:

Rebuilding...
TypeError: hex.includes is not a function
    at rulesForColor (/Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwind-capacitor/src/config/plugin-colors.js:6:12)
    at /Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwind-capacitor/src/config/plugin-colors.js:28:29
    at Array.forEach (<anonymous>)
    at module.exports (/Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwind-capacitor/src/config/plugin-colors.js:27:30)
    at registerPlugins (/Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwindcss/lib/lib/setupContextUtils.js:815:61)
    at createContext (/Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1221:5)
    at createContext (/Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwindcss/lib/processTailwindFeatures.js:44:61)
    at Object.getContext (/Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwindcss/lib/cli/build/plugin.js:202:24)
    at /Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwindcss/lib/cli/build/plugin.js:249:38
    at /Users/macsupport/Downloads/VETCALCULATORS-APP/VETDrugs/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11

**Comment by MattiaFailla** [comment]
+1, same issue on `"vue": "^3.5.13"` and `"tailwind-capacitor": "^1.0.8"`.


The fastest workaround is to remove the following line from `tailwind.config.js` and disable colors:

`require('tailwind-capacitor').colors,`

**Comment by riderx** [comment]
fixed thanks for report
